---
title: "CleanUp"
author: "Shuo Yan"
date: "10/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
```

```{r}
mayor_links_raw = read.csv("/Users/shuoyan/Documents/Social Action Lab/scraping/social_media.csv")
covid_websites_raw = read.csv("/Users/shuoyan/Documents/Social Action Lab/scraping/covid websites.csv", fill = TRUE)

#first row is read in as colnames
covid_first_row = covid_websites_raw[1,]
colnames(covid_websites_raw) = c("gov_link", rep("covid_link", length(covid_websites_raw) - 1))
covid_website =mutate(covid_websites_raw, covid_first_row)

temp = merge(mayor_links_raw,covid_website, by = "gov_link")


```
- Add county

county info is from 
https://simplemaps.com/data/us-cities
```{r}
uscities_raw = read.csv("/Users/shuoyan/Documents/Social Action Lab/scraping/uscities.csv")
texas_info = uscities_raw[uscities_raw$state_name == "Texas", c("city", "county_name")]

file$city = sapply(sapply(file$city, strsplit, split = ","), "[[", 1)
result = merge(file, texas_info, by = "city")

```

```{r}
write_xlsx(result, path = "Texas.xlsx")
```


